"""Provider-neutral contracts and the explicit LumenAgentLoop state machine.

LumenAgentLoop owns model/tool turns, bounded scheduling, approval transitions,
CapabilityGateway execution, result ordering, interactive request boundaries,
cancellation reconciliation and completion gating. Provider transport remains
behind the ModelDriver Interface.
"""

from __future__ import annotations

from lumen.agent_loop.driver import (
    ModelDriver,
    ModelDriverRequest,
    ModelDriverStream,
    ModelProviderError,
    ModelResponseCompleted,
    ModelResponseStarted,
    ModelStopReason,
    ModelStreamEvent,
    ModelTextDelta,
    ModelThinkingDelta,
    ModelToolArgumentsDelta,
    ModelToolCallCompleted,
    ModelToolCallStarted,
    ModelUsage,
    ReplayMismatchError,
    ReplayModelDriver,
    ReplayRecording,
)
from lumen.agent_loop.loop import (
    ApprovalBatchHandler,
    CapabilityVisibility,
    CompletionEvaluator,
    InteractiveContinuation,
    LoopBudgetExceeded,
    LoopCommentaryEmitted,
    LoopCompletionDecided,
    LoopCompletionRejected,
    LoopContextOverflow,
    LoopContinuation,
    LoopEvent,
    LoopEventSink,
    LoopLimits,
    LoopOutcome,
    LoopProtocolError,
    LoopProviderFailure,
    LoopRequestAttempted,
    LoopRequestTimeout,
    LoopRetryScheduled,
    LoopStallObserved,
    LoopState,
    LoopSuspendedContinuation,
    LoopTextEmitted,
    LoopTextRetracted,
    LoopThinkingEmitted,
    LoopToolCallPrepared,
    LoopToolCallsUnsupported,
    LoopToolContinuation,
    LoopToolResultRecorded,
    LoopTransition,
    LoopTruncated,
    LoopTruncationContinuation,
    LoopUsageObserved,
    LoopUsageTotals,
    LoopWaitingOutcome,
    LumenAgentLoop,
    LumenAgentLoopError,
    RequestContinuation,
    SuspendedRequestContinuation,
    ToolRequestContinuation,
    TruncationRequestContinuation,
)
from lumen.agent_loop.pydantic_driver import PydanticAIModelDriver

__all__ = [
    "ApprovalBatchHandler",
    "CapabilityVisibility",
    "CompletionEvaluator",
    "InteractiveContinuation",
    "LoopBudgetExceeded",
    "LoopCommentaryEmitted",
    "LoopCompletionDecided",
    "LoopCompletionRejected",
    "LoopContextOverflow",
    "LoopContinuation",
    "LoopEvent",
    "LoopEventSink",
    "LoopLimits",
    "LoopOutcome",
    "LoopProtocolError",
    "LoopProviderFailure",
    "LoopRequestAttempted",
    "LoopRequestTimeout",
    "LoopRetryScheduled",
    "LoopStallObserved",
    "LoopState",
    "LoopSuspendedContinuation",
    "LoopTextEmitted",
    "LoopTextRetracted",
    "LoopThinkingEmitted",
    "LoopToolCallPrepared",
    "LoopToolCallsUnsupported",
    "LoopToolContinuation",
    "LoopToolResultRecorded",
    "LoopTransition",
    "LoopTruncated",
    "LoopTruncationContinuation",
    "LoopUsageObserved",
    "LoopUsageTotals",
    "LoopWaitingOutcome",
    "LumenAgentLoop",
    "LumenAgentLoopError",
    "ModelDriver",
    "ModelDriverRequest",
    "ModelDriverStream",
    "ModelProviderError",
    "ModelResponseCompleted",
    "ModelResponseStarted",
    "ModelStopReason",
    "ModelStreamEvent",
    "ModelTextDelta",
    "ModelThinkingDelta",
    "ModelToolArgumentsDelta",
    "ModelToolCallCompleted",
    "ModelToolCallStarted",
    "ModelUsage",
    "PydanticAIModelDriver",
    "ReplayMismatchError",
    "ReplayModelDriver",
    "ReplayRecording",
    "RequestContinuation",
    "SuspendedRequestContinuation",
    "ToolRequestContinuation",
    "TruncationRequestContinuation",
]
