from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Any

from markdown_it import MarkdownIt
from markdown_it.renderer import RendererHTML
from markdown_it.token import Token

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
ATLAS_ROOT = REPOSITORY_ROOT / "docs" / "architecture-guide"
OUTPUT_PATH = ATLAS_ROOT / "content.generated.js"
TEXT_SUFFIXES = {".css", ".json", ".md", ".py", ".toml", ".ts", ".tsx", ".yaml", ".yml"}
ROOT_DOCUMENTS = (
    REPOSITORY_ROOT / "README.md",
    REPOSITORY_ROOT / "AGENTS.md",
    REPOSITORY_ROOT / "agent.example.yaml",
    REPOSITORY_ROOT / "docs" / "README.md",
    REPOSITORY_ROOT / "docs" / "commands.md",
    REPOSITORY_ROOT / "docs" / "generated" / "contracts.json",
    REPOSITORY_ROOT / "docs" / "generated" / "provider-reasoning.md",
    REPOSITORY_ROOT / "pyproject.toml",
)
CURRENT_DOCUMENT_ROOTS = (
    REPOSITORY_ROOT / "docs" / "architecture-guide",
    REPOSITORY_ROOT / "docs" / "brand",
    REPOSITORY_ROOT / "docs" / "hooks",
    REPOSITORY_ROOT / "docs" / "skills",
)
LANGUAGES = {
    ".css": "css",
    ".json": "json",
    ".md": "markdown",
    ".py": "python",
    ".toml": "toml",
    ".ts": "typescript",
    ".tsx": "tsx",
    ".yaml": "yaml",
    ".yml": "yaml",
}


class AtlasRenderer(RendererHTML):
    """Render safe Markdown with stable, document-local heading anchors."""

    def heading_open(
        self,
        tokens: Sequence[Token],
        idx: int,
        options: dict[str, Any],
        env: dict[str, Any],
    ) -> str:
        token = tokens[idx]
        heading_text = tokens[idx + 1].content if idx + 1 < len(tokens) else "section"
        base_slug = _slugify(heading_text)
        seen = env.setdefault("heading_slugs", {})
        count = seen.get(base_slug, 0)
        seen[base_slug] = count + 1
        slug = base_slug if count == 0 else f"{base_slug}-{count + 1}"
        return f'<{token.tag} id="{slug}">'


def _slugify(value: str) -> str:
    slug = re.sub(r"[^\w\u3400-\u9fff-]+", "-", value.casefold()).strip("-")
    return slug or "section"


def _iter_content_files() -> Iterable[Path]:
    candidates = set(ROOT_DOCUMENTS)
    for root in CURRENT_DOCUMENT_ROOTS:
        candidates.update(root.rglob("*.md"))
    candidates.update((REPOSITORY_ROOT / "tests").rglob("*.py"))
    for root in (REPOSITORY_ROOT / "src" / "lumen", REPOSITORY_ROOT / "src" / "web" / "src"):
        candidates.update(path for path in root.rglob("*") if path.suffix in TEXT_SUFFIXES)
    candidates.add(REPOSITORY_ROOT / "src" / "web" / "openapi.json")
    for path in sorted(candidates):
        if path.is_file() and path.suffix in TEXT_SUFFIXES:
            yield path


def _markdown_title(content: str, fallback: str) -> str:
    for line in content.splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    return fallback


def _entry(path: Path, markdown: MarkdownIt) -> dict[str, object]:
    content = path.read_text(encoding="utf-8")
    relative_path = path.relative_to(REPOSITORY_ROOT).as_posix()
    digest = hashlib.sha256(content.encode()).hexdigest()
    is_markdown = path.suffix == ".md"
    return {
        "path": relative_path,
        "title": _markdown_title(content, path.name) if is_markdown else path.name,
        "kind": "markdown" if is_markdown else "source",
        "language": LANGUAGES[path.suffix],
        "sha256": digest,
        "bytes": len(content.encode()),
        "lines": len(content.splitlines()),
        "sourceHref": Path("../..").joinpath(relative_path).as_posix(),
        "content": content,
        "html": markdown.render(content, {"heading_slugs": {}}) if is_markdown else None,
    }


def build_payload() -> dict[str, object]:
    markdown = MarkdownIt("commonmark", {"html": False, "linkify": False}, renderer_cls=AtlasRenderer)
    markdown.enable("table")
    entries = [_entry(path, markdown) for path in _iter_content_files()]
    digest_input = "\n".join(f"{entry['path']}:{entry['sha256']}" for entry in entries)
    return {
        "schemaVersion": 1,
        "digest": hashlib.sha256(digest_input.encode()).hexdigest(),
        "entryCount": len(entries),
        "entries": {str(entry["path"]): entry for entry in entries},
    }


def render_output(payload: dict[str, object]) -> str:
    serialized = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    serialized = serialized.replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    return (
        "/* Generated by scripts/build_architecture_atlas.py. Do not edit. */\n"
        f"window.__LUMEN_ATLAS_CONTENT__=Object.freeze({serialized});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the offline Architecture Atlas content snapshot.")
    parser.add_argument("--check", action="store_true", help="Fail when the generated snapshot is stale.")
    args = parser.parse_args()
    rendered = render_output(build_payload())
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != rendered:
            print("Architecture Atlas content snapshot is stale.")
            print("Run: uv run python scripts/build_architecture_atlas.py")
            return 1
        print("Architecture Atlas content snapshot is current.")
        return 0
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPOSITORY_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
