"""Render the reviewed reasoning matrix from the runtime's single catalog."""

# Chinese punctuation is intentional in the generated Chinese documentation.
# ruff: noqa: RUF001

from __future__ import annotations

import argparse
from pathlib import Path

from lumen.provider_catalog import (
    CATALOG_REVISION,
    ENDPOINTS,
    NATIVE_WEB_SEARCH_RULES,
    RULES,
    validate_catalog,
)

OUTPUT = Path(__file__).resolve().parents[1] / "docs/generated/provider-reasoning.md"


def render() -> str:
    validate_catalog()
    lines = [
        "# Provider 模型与推理强度目录", "",
        "<!-- Generated by scripts/export_provider_catalog.py. Do not edit. -->", "",
        f"目录版本：`{CATALOG_REVISION}`。来源：`src/lumen/provider_catalog.py`。", "",
        "这是当前已核对的支持集合，不是全球模型列表。模型 ID 精确匹配；未知版本不继承旧模型规则。",
        "所有行另有 provider_default（不指定应用强度）；别名与有效档位分列。",
        "官方默认表示未传入推理参数时的文档行为，不等于适合全部任务的推荐值；未确认时不猜测。",
        "关闭为 off，OpenAI 原生参数使用 none。预算策略不是供应商原生 effort。", "",
        "## 供应商与端点", "",
        "| 供应商 | 协议 | HTTPS 域名 | Base URL 路径 |",
        "| --- | --- | --- | --- |",
    ]
    for endpoint in ENDPOINTS:
        hosts = (*endpoint.hosts, *(("*" + endpoint.host_suffix,) if endpoint.host_suffix else ()))
        lines.append(f"| {endpoint.vendor} | {', '.join(endpoint.protocols)} | {', '.join(hosts)} | "
                     f"{', '.join(path or '/' for path in endpoint.paths)} |")
    lines += ["", "协议前缀只是 Adapter 选择。无自定义端点时使用对应 SDK 的官方默认；",
              "环境变量覆盖也参与识别。自定义代理可用 reasoning_profile 显式引用目录规则，",
              "同时必须匹配模型 ID 和协议，不能覆盖已知端点的供应商身份。", "",
              "## 模型与档位", "",
              "| Profile ID | 供应商 | 精确模型 ID | 协议 | 有效档位 | 兼容别名 | 官方默认 |"
              " 参数 Adapter | 核对日期 |",
              "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for rule in RULES:
        aliases = ", ".join(f"{alias} → {target}" for alias, target in rule.aliases) or "—"
        lines.append(f"| {rule.key} | {rule.vendor} | {', '.join(rule.models)} | "
                     f"{', '.join(rule.protocols)} | {', '.join(rule.levels) or '不支持调节'} | "
                     f"{aliases} | {rule.default_level or '未确认'} | {rule.codec} | {rule.reviewed_on} |")
    lines += ["", "## 官方依据与映射说明", ""]
    for rule in RULES:
        sources = " · ".join(f"[官方资料 {index}]({url})" for index, url in enumerate(rule.sources, 1))
        lines.append(f"- **{rule.key}**：{sources}。{rule.note}")
    lines += [
        "",
        "## 模型原生联网搜索",
        "",
        "`native_web_search.mode: auto` 只对下表中的精确模型、供应商与协议组合默认开启。",
        "未知模型保持关闭；可用 `enabled` 显式声明部署支持，或用 `disabled` 明确关闭。",
        "此工具由模型提供方在服务端执行，不经过 Lumen 的 MCP CapabilityGateway。",
        "",
        "| 供应商 | 精确模型 ID | 协议 | 搜索上下文参数 | 核对日期 | 官方依据 |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for rule in NATIVE_WEB_SEARCH_RULES:
        sources = " · ".join(
            f"[官方资料 {index}]({url})" for index, url in enumerate(rule.sources, 1)
        )
        lines.append(
            f"| {rule.vendor} | {', '.join(rule.models)} | {', '.join(rule.protocols)} | "
            f"{'发送' if rule.sends_search_context_size else '省略'} | "
            f"{rule.reviewed_on} | {sources} |"
        )
    lines += ["", "维护方法见 [Provider 层维护约定](../architecture-guide/15-provider-catalog.md)。", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != expected:
            print("Provider catalog document is stale; run scripts/export_provider_catalog.py")
            return 1
        print("Provider catalog document is current.")
    else:
        OUTPUT.write_text(expected)
        print(f"Wrote {OUTPUT.relative_to(OUTPUT.parents[2])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
